# <span style="color:red"> QTM 151 - Quiz 3 </span>

## Please submit as an HTML file

<font size = "5" >
This quiz is open book 

- You can use the lecture notes
- You will get partial credit for attempting the questions
- To get full credit, the code should run as intended
- You should <span style="color:red"> NOT </span> communicate with other students

Print the following message: <br>

"I will abide by Emory's code of conduct"

In [1]:
# Write your answer here:

print("I will abide by Emory's code of conduct")

I will abide by Emory's code of conduct

<font size = "5">

Import the libraries "numpy" and "pandas"

In [2]:
import numpy as np 
import pandas as pd


<font size = "5">

(1) Replace values in a column

<font size = "3">

- Load the data from "constructors.csv", assigning it to a DataFrame.
- In the "nationality" column, replace the values "British", "Japanese", and "Irish" with "UK", "Japan", and "Ireland", respectively.
- For full credit, do this by using the ``.replace`` command **one time**

In [36]:
# Your answer here
df = pd.read_csv("data_raw/constructors.csv")

df["nationality"] = df["nationality"].replace(["British", "Japanese", "Irish"], 
                            ["UK", "Japan", "Ireland"])

df["nationality"]

0            UK
1        German
2            UK
3        French
4       Italian
         ...
206          UK
207    American
208          UK
209     Italian
210      French
Name: nationality, Length: 211, dtype: object

<font size = "5">

(2) Aggregate and query

<font size = "3">

Import the data from "sprint_results.csv" and assign it to a DataFrame. Do the following:

- Extract the subset corresponding to 'constructorId == 51' using ```.query()```
- Group by the column "driverId", and then aggregate the maximum over the "laps" column for each driver.
- Extract the subset of drivers with maximum of laps $\ge 20$. Assign this to a DataFrame with a name of your choice.

For full credit, perform all the steps in bullet points above in a **single line** using chaining. (If you use line breaks or wrap in parentheses it doesn't literally need to be one line).

**Hint:** I only see your final submission, not the code you wrote along the way. It might be easier to break it up into multiple lines, then combine when you're done.

In [15]:
# Your answer here
df_sprint = pd.read_csv("data_raw/sprint_results.csv")

sprint_agg = (df_sprint.query("constructorId == 51")
                       .groupby(["constructorId","driverId"])
                        .agg(max_laps = ("laps","max"),)
                            .query("max_laps >= 20"))

print(sprint_agg)

                        max_laps
constructorId driverId
51            8               24
              822             24
              841             24
              855             24

<font size = "5">

(3) Recode a numeric column

<font size = "3">

- Import data from "races.csv" and assign it to a DataFrame
- Recode the "year" column into a new column "year_brackets"
with the following categories

$\qquad$ ``` ["1950-1965","1966-1980","1981-onwards"] ```

The easiest method is ``pd.cut()`` but you are not required to use this.

In [20]:
# Your answer here
df_races = pd.read_csv("data_raw/races.csv")

group_bins = [1949, 1965, 1980, float("inf")] 
group_labels = ["1950-1965","1966-1980","1981-onwards"]
df_races["year_brackets"] = pd.cut(df_races["year"],
                                    bins = group_bins,
                                    right = True,
                                    labels = group_labels)

df_races["year_brackets"]

0       1981-onwards
1       1981-onwards
2       1981-onwards
3       1981-onwards
4       1981-onwards
            ...
1097    1981-onwards
1098    1981-onwards
1099    1981-onwards
1100    1981-onwards
1101    1981-onwards
Name: year_brackets, Length: 1102, dtype: category
Categories (3, object): ['1950-1965' < '1966-1980' < '1981-onwards']

<font size = "5">

(4) Aggregate and sort

<font size = "3">

Import the data from "sprint_results.csv" and assign it to a DataFrame (or use the same DataFrame you created in problem (2)). Do the following:

- Group by "driverId", and then aggregate the average (mean) over the "laps" column.
- Sort the teams by average laps in **descending** order using ``.sort_values()``. Assign this to a DataFrame with a name of your choice.

For full credit, perform both steps in bullet points above in a **single line** using chaining. (If you use line breaks or wrap in parentheses it doesn't literally need to be one line).

**Hint:** Same hint as problem 2. You can chain commands together later.

In [31]:
# Your answer here

sorted_data = (df_sprint.groupby("driverId").agg(avg_sprint = ("laps", "mean"))
                                                .sort_values(by = "avg_sprint", ascending = False))

sorted_data

          avg_sprint
driverId
825        22.666667
1          21.166667
832        21.166667
854        21.166667
852        21.166667
849        21.166667
847        21.166667
846        21.166667
844        21.166667
839        21.166667
840        21.166667
830        21.166667
822        21.166667
817        21.166667
815        21.000000
20         20.833333
8          20.500000
841        19.666667
853        19.666667
848        18.666667
842        18.166667
9          18.000000
4          17.333333
855        15.666667

<font size = "5">

(5) Rename column

<font size = "3">

- Import the data from "sprint_results.csv" and assign it to a DataFrame (or use the same DataFrame you created in problem (2))

- Rename the column "time" to "time_unformatted". The names of the other columns should be left intact.

- Print (or display) the DataFrame to ensure the column was renamed correctly.

In [28]:
# Your answer here

df_sprint.rename(columns={"time" : "time_unformatted"}, inplace=True)
print(df_sprint.columns.values)

['resultId' 'raceId' 'driverId' 'constructorId' 'number' 'grid' 'position'
 'positionText' 'positionOrder' 'points' 'laps' 'time_unformatted'
 'milliseconds' 'fastestLap' 'fastestLapTime' 'statusId']

<font size = "5">

(6) Merge dataset

<font size = "3">

- Import the data from "sprint_results.csv" and "constructors.csv", assigning them to two DataFrames (you can also re-use the DataFrames you created above.)

- Create a new dataset with  ``pd.merge()``. Treat "sprint_results.csv" as the primary dataset and "constructors.csv" as the secondary dataset. The merge should be based on the column "constructorId".
the column "constructorId"
- To get full credit **ONLY** merge the "nationality" column from the secondary dataset (not all the columns)
- Print (or display) the resulting merged DataFrame to the screen.

**Hint**: Before you start typing "pd.merge(...)" try printing out the two DataFrames you want to merge, excluding any columns that shouldn't be included.

In [34]:
# Your answer here

df_merge = pd.merge(left = df_sprint, right = df[["constructorId", "nationality"]], 
    on = "constructorId", how = "left")

df_merge

,resultId,raceId,driverId,constructorId,number,grid,position,positionText,positionOrder,points,laps,time_unformatted,milliseconds,fastestLap,fastestLapTime,statusId,nationality
0,1,1061,830,9,33,2,1,1,1,3,17,25:38.426,1538426,14,1:30.013,1,Austrian
1,2,1061,1,131,44,1,2,2,2,2,17,+1.430,1539856,17,1:29.937,1,German
2,3,1061,822,131,77,3,3,3,3,1,17,+7.502,1545928,17,1:29.958,1,German
3,4,1061,844,6,16,4,4,4,4,0,17,+11.278,1549704,16,1:30.163,1,Italian
4,5,1061,846,1,4,6,5,5,5,0,17,+24.111,1562537,16,1:30.566,1,UK
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
115,116,1095,840,117,18,15,16,16,16,0,24,+50.700,1862007,4,1:15.425,1,UK
116,117,1095,839,214,31,6,17,17,17,0,24,+51.756,1863063,5,1:16.097,1,French
117,118,1095,4,214,14,7,18,18,18,0,24,+53.985,1865292,5,1:14.764,1,French
118,119,1095,849,3,6,16,19,19,19,0,24,+1:16.850,1888157,4,1:16.525,1,UK
119,120,1095,848,3,23,11,\N,R,20,0,12,\N,\N,4,1:15.998,31,UK